apiVersion: v2
name: snappass
description: Install the SnapPass secret tool
home: "https://github.com/lmacka/helm-snappass"
type: application
version: 0.1.12
appVersion: "1.6.2"
icon: https://lmacka.github.io/helm-snappass/img/pinterest-logo.png
keywords:
  - pinterest
  - password
  - secret
  - security
  - secure
  - share
sources:
  - https://github.com/lmacka/helm-snappass
maintainers:
  - name: lmacka
    url: https://github.com/lmacka
kubeVersion: ">=1.21.0-0"
dependencies:
  - name: valkey
    condition: valkey.enabled
    version: ~2.1
    repository: https://groundhog2k.github.io/helm-charts/
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Gunicorn workers configuration support
    - kind: changed
      description: Updated container image to use gunicorn
    - kind: fixed
      description: Fixed gunicorn logging
