apiVersion: v2
name: snappass
description: Install the SnapPass secret tool
home: "https://github.com/lmacka/helm-snappass"
type: application
version: 0.1.5
appVersion: "1.6.2"
icon: https://lmacka.github.io/helm-snappass/img/pinterest-logo.png
keywords:
  - pinterest
  - password
  - secret
  - security
  - secure
  - share
sources:
  - https://github.com/lmacka/helm-snappass
maintainers:
  - name: lmacka
    url: https://github.com/lmacka
kubeVersion: ">=1.21.0-0"
dependencies:
  - name: redis
    condition: redis.enabled
    version: ~19
    repository: https://charts.bitnami.com/bitnami
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: string replace in deployment for HELMRELEASENAME
    - kind: added
      description: optional init container to wait for redis to be ready
    - kind: fixed
      description: ingress class deprecation
